params:
  env:
    name: GatheringEasy-v0
    seed: 123

  loss:
    name: GatheringEasyLoss
    target_file: None
    weight:
      dist: 1
    loss_type: diff

  config:
    n_iters: 500
    init_range:
      v: ((0.0, 0.0, 0.0), (0.0, 0.0, 0.0))
      p: ((0.55, 0.45, 0.5), (0.55, 0.45, 0.5))
    optim:
      type: 'Adam'
      lr: 1e-4
      beta_1: 0.9
      beta_2: 0.99
      epsilon: 1e-8

