params:
  env:
    name: Transporting-v0
    seed: 234
  loss:
    name: SHACLoss
    target_file: Transporting.pkl
    weight:
      density: 1
      sdf: 100
      contact: 0
      is_soft_contact: False

  config:
    actor_learning_rate: 1e-4 # adam
    critic_learning_rate: 1e-4 # adam
    lr_schedule: linear # ['constant', 'linear']
    target_critic_alpha: 0.2
    critic_iterations: 128
    critic_method: td-lambda # ['td-lambda', 'one-step']
    lam: 0.95
    num_batch: 1
    gamma: 0.99
    betas: [0.9, 0.999] # adam
    max_epochs: 20000
    steps_num: 32
    grad_norm: 1.0
    truncate_grads: True
    num_actors: 1
    save_interval: 400
    device: cuda:0



