type: AgentRigid
effectors:
  - type: Rigid
    params:
      init_pos: (0.5, 0.6, 0.5)
      init_euler: (0.0, 0.0, 0.0)
      action_dim: 6
      action_scale_p: (1.0, 1.0, 1.0, 1.0, 1.0, 1.0)
      action_scale_v: (1.0, 1.0, 1.0, 1.0, 1.0, 1.0)
    mesh:
      file: roller.obj
      scale: (0.25, 0.25, 0.25)
      euler: (0.0, 0.0, 0.0)
      material: PLATE
      softness: 100.0
    boundary:
      type: cube
      lower: (0.3, 0.13, 0.3)
      upper: (0.7, 0.25, 0.7)
sensors:
  - type: GridSensor3D
    params:
      sesnor_name: gridsensor3d
      cell_arc: 2
      lat_angle_north: 90
      lat_angle_south: 90
      lon_angle: 180
      max_distance: 1.0
      min_distance: 0.0
      distance_normalization: 1
  - type: GridSensor2D
    params:
      sensor_name: gridsensor2d
      cell_size: 0.05
      x_range: 1
      z_range: 1