params:
  env:
    name: Pouring-v0
    seed: 123
  loss:
    name: PPOLoss
    target_file: Pouring.pkl
    weight:
      density: 21
      sdf: 21
      contact: 0
      is_soft_contact: False

  config:
    deterministic_eval: False
    action_scaling: False
    ReplayBufferSize: 20000
    max_epochs: 60
    step_per_epochs: 2240
    repeat_per_collect: 1
    episode_per_test: 1
    batch_size: 256
    step_per_collect: 2240
    num_envs: 1
    lr: 0.00005
    betas: [0.9, 0.999]
    device: cuda:0
